-- ==============================================================================
-- TABELA DE PERÍMETROS BLOQUEADOS / ÁREAS RESTRITAS (CONDOMÍNIOS, ÁREAS PRIVADAS)
-- Impede a abertura de Ordens de Serviço (OS) dentro dos limites demarcados
-- ==============================================================================

create table if not exists public.perimetros_bloqueados (
    id bigint generated by default as identity primary key,
    nome text not null,
    justificativa text not null default 'Área particular / Condomínio fechado não atendido pela concessão pública municipal.',
    tipo text not null default 'condominio', -- 'condominio', 'particular', 'outros'
    coordenadas jsonb not null, -- Array de coordenadas [[lng, lat], [lng, lat], ...] ou GeoJSON Polygon
    ativo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by uuid references auth.users(id)
);

-- Índices úteis
create index if not exists idx_perimetros_bloqueados_ativo on public.perimetros_bloqueados(ativo);

-- Habilitar RLS (Row Level Security)
alter table public.perimetros_bloqueados enable row level security;

-- Política de leitura: Qualquer usuário autenticado ou anônimo que abra OS pode ler os perímetros
drop policy if exists "Permitir leitura de perímetros ativos" on public.perimetros_bloqueados;
create policy "Permitir leitura de perímetros ativos"
    on public.perimetros_bloqueados for select
    using (true);

-- Política de escrita: Administradores e usuários autenticados
drop policy if exists "Permitir inserção de perímetros" on public.perimetros_bloqueados;
create policy "Permitir inserção de perímetros"
    on public.perimetros_bloqueados for insert
    to authenticated
    with check (true);

drop policy if exists "Permitir atualização de perímetros" on public.perimetros_bloqueados;
create policy "Permitir atualização de perímetros"
    on public.perimetros_bloqueados for update
    to authenticated
    using (true)
    with check (true);

drop policy if exists "Permitir exclusão de perímetros" on public.perimetros_bloqueados;
create policy "Permitir exclusão de perímetros"
    on public.perimetros_bloqueados for delete
    to authenticated
    using (true);
